[bench]
name = "DVSGesture_CNN_float32_Linux"
seed = 2
first_run = 1
last_run = 1
plugins = ['qualia_plugin_snn']

[learningframework]
kind = 'PyTorch'
#params.accelerator = 'cpu'
params.devices = 1

[experimenttracking]
kind = 'ClearML'
params.project_name = 'qualia-plugin-snn'
params.task_name = 'DVSGesture_CNN_float32_Linux'

[deploy]
#target = 'SPLEAT'
#converter.kind = 'SPLEAT'
#converter.params.output_feature_maps = [1, 2, 3, 4]
target = 'Linux'
converter.kind = 'QualiaCodeGen'
quantize = ['float32']
optimize = ['']

[dataset]
kind = 'DVSGesture'
#kind = 'DVSGestureWithPreprocessing'
params.path = "data/DVS128Gesture/"
params.data_type = 'frame'
#params.duration = 100000
#params.timesteps = 8

[[preprocessing]]
kind = "IntegrateEventsByFixedDuration"
params.duration = 100000

[[preprocessing]]
kind = "Group2TimeStepsBySample"
params.timesteps = 8

[[preprocessing]]
kind = "Class2BinMatrix"

[[data_augmentation]]
kind = "Mixup"

[[data_augmentation]]
kind = "Rotation2D"
params.angle = [-5, 5]

[[data_augmentation]]
kind = "Crop"
params.size = [112, 112]
params.padding = [16, 16]

[model_template]
kind = 'CNN'
epochs = 90
batch_size = 2048

[model_template.optimizer]
kind = "AdamW"
params.lr               = 0.025
#params.weight_decay	= 1e-3

[model_template.optimizer.scheduler]
kind = "MultiStepLR"
params.milestones	= [20, 40, 60, 75]
params.gamma		= 0.1

[[model]]
name = 'dvsgesture_cnn'
params.dims = 2
#params.filters = [3, 6, 16, 10]
#params.filters = [6, 12, 32, 10]
params.filters = [16, 24, 32, 48, 64, 11]
params.kernel_sizes = [7, 3, 3, 3, 3, 3]
params.pool_sizes = [0, 0, 0, 0, 0, 0]
params.strides = [2, 2, 2, 2, 2, 2]
params.paddings = [3, 1, 1, 1, 1, 1]
params.fc_units = []
params.gsp = true
params.batch_norm = true
disabled = false
