[bench]
name = "DVSGesture_SCNN_float32_Linux"
seed = 2
first_run = 1
last_run = 1
plugins = ['qualia_plugin_snn']

[learningframework]
kind = 'SpikingJelly'

[experimenttracking]
kind = 'ClearML'
params.project_name = 'qualia-plugin-snn'
params.task_name = 'DVSGesture_SCNN_float32_Linux'

[deploy]
#target = 'SPLEAT'
#converter.kind = 'SPLEAT'
#converter.params.output_feature_maps = [1, 2, 3, 4]
target = 'Linux'
converter.kind = 'KerasCNN2C'
quantize = ['float32']
optimize = ['']

[dataset]
kind = 'DVSGesture'
params.path = "data/DvsGesture/"
params.data_type = 'frame'
params.duration = 50000

[[preprocessing]]
kind = "Class2BinMatrix"

[model_template]
kind = 'SCNN'
epochs = 30
batch_size = 1024

[model_template.optimizer]
kind = "Adam"
params.lr               = 0.01
params.weight_decay	= 5e-4

[model_template.optimizer.scheduler]
kind = "MultiStepLR"
params.milestones	= [10, 20, 25]
params.gamma		= 0.1

[[model]]
name = 'dvsgesture_scnn'
params.dims = 2
#params.filters = [3, 6, 16, 10]
#params.filters = [6, 12, 32, 10]
params.filters = [16, 24, 32, 48, 11]
params.kernel_sizes = [7, 3, 3, 3, 3]
params.pool_sizes = [0, 0, 0, 0, 0]
params.strides = [2, 2, 2, 2, 2]
params.paddings = [3, 1, 1, 1, 1]
params.fc_units = []
params.timesteps = 4
params.v_threshold = 1.0
#params.v_reset = 0.0
params.tau = 2.0
params.gsp = true
params.batch_norm = true
disabled = false
