[bench]
name        = 'GSC_SResNetv1-8_no_fused_ICONIP_livemfcc_LSQ4_and_8_train'
seed        = 2
first_run   = 1
last_run    = 3
plugins     = ['qualia_plugin_snn']

[learningframework]
kind                = 'SpikingJelly'
params.devices      = 4
#params.devices     = 1
params.precision    = '16-mixed'

[deploy]
target          = 'Linux'
converter.kind  = 'QualiaCodeGen'
quantize        = ['float32']
optimize        = ['']
compress        = [1]

[dataset]
kind            = 'GSC'
params.variant  = 'v2'
params.path     = "data/SpeechCommands/"
params.subset   = 'no_background_noise'

[[preprocessing]]
kind            = 'Class2BinMatrix'

[[preprocessing]]
kind            = 'Normalize'
params.method   = 'z-score'
params.axis     = 0
params.debug    = true

[[data_augmentation]]
kind            = 'GaussianNoise'
params.sigma    = 0.00175

[[data_augmentation]]
kind            = 'TimeWarping'
params.sigma    = 0.0675

[[data_augmentation]]
kind            = 'TimeShifting'
params.alpha    = 1.0

[[data_augmentation]]
kind                            = 'MFCC'
params.evaluate                 = true
params.sample_rate              = 16000
#params.n_mfcc                   = 64
params.n_mfcc                   = 10
params.log_mels                 = true
params.melkwargs.n_fft          = 1024
params.melkwargs.n_mels         = 40
#params.melkwargs.win_length     = 1024
params.melkwargs.win_length     = 640
#params.melkwargs.hop_length     = 128
fparams.melkwargs.hop_length    = 320
params.melkwargs.f_min          = 20
params.melkwargs.f_max          = 4000
params.melkwargs.pad            = 320
params.melkwargs.center         = false

[[postprocessing]]
kind                = "QuantizationAwareTraining"
export              = true
params.epochs       = 20
#params.batch_size   = 800
params.batch_size   = 200
params.model.params.quantize_linear             = true
params.model.params.quant_params.bits           = 8
params.model.params.quant_params.quantype       = "fake"
params.model.params.quant_params.roundtype      = "nearest"
params.model.params.quant_params.range_setting  = "minmax"
params.model.params.quant_params.input.quant_enable=false
params.model.params.quant_params.LSQ            = true

[model_template]
kind                = 'SResNet'
epochs              = 0
#batch_size          = 800
batch_size          = 200
load                = true
train               = false
params.input_shape  = [49, 10]
params.batch_norm   = true
params.bn_momentum  = 0.1
params.dims         = 1
params.prepool      = 1
params.timesteps    = 4
params.neuron.kind                  = 'LIFNode'
params.neuron.params.v_threshold    = 1.0
params.neuron.params.v_reset        = 0
params.neuron.params.tau            = 2.0


[model_template.optimizer]
kind                = "Adam"
params.lr           = 0.004
params.weight_decay = 0

[model_template.optimizer.scheduler]
kind            ='CosineAnnealingLR'
params.T_max    = 200
params.eta_min  = 0.00001

# With no_Fuse - layer_wise 8

[[model]]
name                        = 'GSC_SResNet-8_ICONIP_float'
params.filters              = [64, 64]
params.kernel_sizes         = [7, 3]
params.paddings             = [3, 1]
params.strides              = [1, 1]
params.num_blocks           = [3]
params.batch_norm           = true
update.quant_params.bits    = 8
disabled                    = false

# With no_Fuse - layer_wise 6

[[model]]
name                        = 'GSC_SResNet-8_ICONIP_float'
params.filters              = [64, 64]
params.kernel_sizes         = [7, 3]
params.paddings             = [3, 1]
params.strides              = [1, 1]
params.num_blocks           = [3]
params.batch_norm           = true
update.quant_params.bits    = 6
disabled            = false

# With no_Fuse - layer_wise 4

[[model]]
name                        = 'GSC_SResNet-8_ICONIP_float'
params.filters              = [64, 64]
params.kernel_sizes         = [7, 3]
params.paddings             = [3, 1]
params.strides              = [1, 1]
params.num_blocks           = [3]
params.batch_norm           = true
update.quant_params.bits    = 4
disabled            = false
